/* Test Script */
--
/*
   Multi
   Line */
CREATE TABLE /*<schema>.*/"TABLEWORK"
   (	"ID" NUMBER(11,0) DEFAULT NULL,
   "V99" VARCHAR2(40) DEFAULT '' NOT NULL ENABLE,
   "V99" VARCHAR2(2000) DEFAULT '' NOT NULL ENABLE,
   "V99" VARCHAR2(50) DEFAULT '' NOT NULL ENABLE,
   "V99" VARCHAR2(1) DEFAULT '4' NOT NULL ENABLE,
   "V99" VARCHAR2(50) DEFAULT ' ' NOT NULL ENABLE,
   "V99" VARCHAR2(50) DEFAULT ' ' NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" VARCHAR2(1) DEFAULT '4' NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" VARCHAR2(50) DEFAULT '' NOT NULL ENABLE,
   "V99" VARCHAR2(255) DEFAULT ' ' NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS') NOT NULL ENABLE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" VARCHAR2(50) DEFAULT ' ' NOT NULL ENABLE,
   "V99" DATE,
   "V99" VARCHAR2(400),
   "V99" VARCHAR2(1) DEFAULT 'N',
   "V99" VARCHAR2(1) DEFAULT ' ',
   "V99" VARCHAR2(255) DEFAULT '-',
   "V99" VARCHAR2(50),
   "V99" VARCHAR2(50) DEFAULT ' ',
   "V99" NUMBER(2,1),
   "V99" VARCHAR2(1) DEFAULT '0' NOT NULL ENABLE,
   "V99" VARCHAR2(10),
	"VRAAGBUNDELING40" CHAR(1) DEFAULT 'N',
   "V99" DATE,
   "V99" DATE,
   "V99" VARCHAR2(50),
   "V99" DATE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" VARCHAR2(4000 CHAR),
   "V99" VARCHAR2(15),
   "V99" VARCHAR2(1) DEFAULT 'N',
   "V99" VARCHAR2(1) DEFAULT 'N',
   "V99" VARCHAR2(1) DEFAULT 'N',
   "V99" VARCHAR2(1) DEFAULT 'N',
   "V99" DATE DEFAULT TO_DATE((TO_CHAR(SYSDATE,'MM-DD-YYYY HH24:MI:SS')),'MM-DD-YYYY HH24:MI:SS'),
   "V99" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
   "V99" DATE,
   "V99" VARCHAR2(50),
   "V99" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COCON"
  CREATE UNIQUE INDEX /*<schema>.*/"PK_WORK" ON /*<schema>.*/"WORK" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COCON"
ALTER TABLE /*<schema>.*/"WORK" ADD CONSTRAINT "PK_WORK" PRIMARY KEY ("ID")
  USING INDEX /*<schema>.*/"PK_WORK"  ENABLE
